Revert "ci(docker): Add docker CI"
Too big to run on GitHub free runner.
Error: no space left on device

This reverts commit fc029d7beae6c79aa90cdf1dc84aeea2c138bd11.

Signed-off-by: 陳鈞 <jim60105@gmail.com>